apiVersion: v1
kind: Secret
metadata:
  name: test1
  annotations:
    webhoook-enabled: "true"
type: Opaque
data:
  webhook.crt: dGVzdE1lc3NhZ2VQbGVhc2VJZ25vcmU=
  webhook.key: dGVzdE1lc3NhZ2VQbGVhc2VJZ25vcmUx
---
apiVersion: v1
kind: Secret
metadata:
  name: test2
  annotations:
    justNothing: "nothing"
type: Opaque
data:
  username: YWRtaW4=
  password: UEBzc3cwcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: test3
  annotations:
    webhoook-enabled: "true"
type: Opaque
data:
  verySecret: dG9wU2VjcmV0
